import "./system/first-join.js";
import "./system/system-index.js";
import "./system/commands/ver.js";
import "./system/commands/hhelp.js";
import "./system/commands/hmenu.js";
import "./system/commands/dep.js";
import "./system/commands/depall.js";
import "./system/commands/with.js";
import "./system/commands/withall.js";
import "./system/commands/balmenu.js";
import "./system/commands/bal.js";
import "./system/commands/transfer.js";
import "./system/commands/fasttravel.js";
import "./system/commands/forcemarket.js";
import "./system/menu/clock.js";
import "./system/menu/main-menu.js";
import "./system/menu/page1-joinmenu.js";
import "./modules/playerinfo/registered-tags.js";
import "./modules/playerinfo/utils.js";
import "./modules/economy/core.js"
import "./modules/economy/food-market.js"